version: '3'
services:
  hugo:
    image: monachus/hugo
    ports:
     - "1313:1313"
    environment:
       HUGO_BASE_URL: /
    volumes:
       - .:/usr/share/blog
  wkhtmltopdf:
    depends_on:
       - hugo
    image: surnet/alpine-wkhtmltopdf:3.9-0.12.5-full
    command: --disable-external-links --no-print-media-type --page-size A4 --zoom 0.8 --viewport-size 1680 --javascript-delay 2000 --disable-smart-shrinking --margin-bottom 0 --margin-left 0 --margin-right 0 --margin-top 0 http://hugo:1313/ /hugo/dist/cv.pdf
    volumes:
      - .:/hugo
